theme: jekyll-theme-giellalt
title: Dictionary for Finnish ⇒ Tundra Nenets
description: An electronic dictionary from Finnish to Tundra Nenets

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
